services:
  car-log-db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: car-log-db
    volumes:
      - car-log-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - car-log-network

  car-log-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-log-app
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '3000:3000'
    depends_on:
      - car-log-db
      - car-log-redis
    networks:
      - car-log-network
    volumes:
      - .:/app
      - /app/node_modules

  car-log-pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: car-log-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - car-log-db
    volumes:
      - car-log-pgadmin:/var/lib/pgadmin

  car-log-redis:
    image: redis:latest
    container_name: car-log-redis
    ports:
      - '6379:6379'
    networks:
      - car-log-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis:/data
    restart: always

volumes:
  redis:
    driver: local
    name: car-log-redis
  car-log-db:
    driver: local
    name: car-log-db
  car-log-pgadmin:
    driver: local
    name: car-log-pgadmin

networks:
  car-log-network:
    driver: bridge
